spring:
  application:
    name: spring-cloud-eureka-feign-client

server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: false
    eurekaServerDNSName: localhost
    eurekaServerPort: 8761
    eurekaServerURLContext: eureka